[build]
command = "npm run build"
publish = "dist/roseville-bike-ride/browser"

[functions]
directory = "dist/roseville-bike-ride/server"

[[redirects]]
from = "/*"
to = "/.netlify/functions/main.server"
status = 200
force = true